#pragma once

/*
 * CrowPanel Advanced 10.1" ESP32-P4 + ESP32-C6 ESP-Hosted override.
 *
 * Arduino's stock esp32p4 variant is built for a generic 4-bit, 40 MHz SDIO
 * C6 link with reset on GPIO54. Elecrow's 7/9/10.1" manufacturer project uses
 * 1-bit, 10 MHz SDIO and reset on GPIO32. Keeping the generic defaults can make
 * the C6 transport unstable enough to trigger scan/connect hangs and crashes.
 */
#include <sdkconfig.h>

#ifdef CONFIG_SOC_SDMMC_IO_POWER_EXTERNAL
#undef CONFIG_SOC_SDMMC_IO_POWER_EXTERNAL
#endif

#ifdef CONFIG_ESP_HOSTED_SDIO_4_BIT_BUS
#undef CONFIG_ESP_HOSTED_SDIO_4_BIT_BUS
#endif
#ifndef CONFIG_ESP_HOSTED_SDIO_1_BIT_BUS
#define CONFIG_ESP_HOSTED_SDIO_1_BIT_BUS 1
#endif

#ifdef CONFIG_ESP_HOSTED_SDIO_BUS_WIDTH
#undef CONFIG_ESP_HOSTED_SDIO_BUS_WIDTH
#endif
#define CONFIG_ESP_HOSTED_SDIO_BUS_WIDTH 1

#ifdef CONFIG_ESP_HOSTED_SDIO_CLOCK_FREQ_KHZ
#undef CONFIG_ESP_HOSTED_SDIO_CLOCK_FREQ_KHZ
#endif
#define CONFIG_ESP_HOSTED_SDIO_CLOCK_FREQ_KHZ 10000

#ifdef CONFIG_ESP_HOSTED_SDIO_GPIO_RESET_SLAVE
#undef CONFIG_ESP_HOSTED_SDIO_GPIO_RESET_SLAVE
#endif
#define CONFIG_ESP_HOSTED_SDIO_GPIO_RESET_SLAVE 32

#ifdef CONFIG_ESP_HOSTED_GPIO_SLAVE_RESET_SLAVE
#undef CONFIG_ESP_HOSTED_GPIO_SLAVE_RESET_SLAVE
#endif
#define CONFIG_ESP_HOSTED_GPIO_SLAVE_RESET_SLAVE 32

#ifdef CONFIG_ESP_HOSTED_PRIV_SDIO_PIN_D1_4BIT_BUS_SLOT_1
#undef CONFIG_ESP_HOSTED_PRIV_SDIO_PIN_D1_4BIT_BUS_SLOT_1
#endif
#ifndef CONFIG_ESP_HOSTED_PRIV_SDIO_PIN_D1_1BIT_BUS_SLOT_1
#define CONFIG_ESP_HOSTED_PRIV_SDIO_PIN_D1_1BIT_BUS_SLOT_1 15
#endif

#ifdef CONFIG_ESP_SDIO_4_BIT_BUS
#undef CONFIG_ESP_SDIO_4_BIT_BUS
#endif
#ifndef CONFIG_ESP_SDIO_1_BIT_BUS
#define CONFIG_ESP_SDIO_1_BIT_BUS 1
#endif

#ifdef CONFIG_ESP_SDIO_BUS_WIDTH
#undef CONFIG_ESP_SDIO_BUS_WIDTH
#endif
#define CONFIG_ESP_SDIO_BUS_WIDTH 1

#ifdef CONFIG_ESP_SDIO_CLOCK_FREQ_KHZ
#undef CONFIG_ESP_SDIO_CLOCK_FREQ_KHZ
#endif
#define CONFIG_ESP_SDIO_CLOCK_FREQ_KHZ 10000

#ifdef CONFIG_ESP_SDIO_GPIO_RESET_SLAVE
#undef CONFIG_ESP_SDIO_GPIO_RESET_SLAVE
#endif
#define CONFIG_ESP_SDIO_GPIO_RESET_SLAVE 32

#ifdef CONFIG_ESP_GPIO_SLAVE_RESET_SLAVE
#undef CONFIG_ESP_GPIO_SLAVE_RESET_SLAVE
#endif
#define CONFIG_ESP_GPIO_SLAVE_RESET_SLAVE 32
